<?php

namespace ContainerQyDoT5X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XCU4G7nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xCU4G7n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xCU4G7n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fileUploader' => ['privates', 'App\\Service\\FileUploader', NULL, 'Cannot autowire service "App\\Service\\FileUploader": argument "$targetDirectory" of method "__construct()" has no type-hint, you should configure its value explicitly.'],
        ], [
            'fileUploader' => 'App\\Service\\FileUploader',
        ]);
    }
}
