<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV158tZ2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV158tZ2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV158tZ2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV158tZ2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV158tZ2\App_KernelDevDebugContainer([
    'container.build_hash' => 'V158tZ2',
    'container.build_id' => '736d2d58',
    'container.build_time' => 1640274897,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV158tZ2');
