<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGmzMpCo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGmzMpCo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGmzMpCo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGmzMpCo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGmzMpCo\App_KernelDevDebugContainer([
    'container.build_hash' => 'GmzMpCo',
    'container.build_id' => 'e654b14b',
    'container.build_time' => 1635943972,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGmzMpCo');
