<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQJxce8P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQJxce8P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQJxce8P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQJxce8P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQJxce8P\App_KernelDevDebugContainer([
    'container.build_hash' => 'QJxce8P',
    'container.build_id' => '44925308',
    'container.build_time' => 1636557389,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQJxce8P');
